# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  - master
  - branch-*

pr:
  - master
  - branch-*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud - Devtility'
    organization: 'devtility'
    scannerMode: 'MSBuild'
    projectKey: 'asmrefs-baseliner'
    projectName: 'AsmRefs Baseliner'
    projectVersion: '0.1'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\src\DumpAsmRefs\bin'
    Contents: |
      **\dump**
      **\Microsoft.Extensions**
    TargetFolder: '$(Build.ArtifactStagingDirectory)\binaries'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\src\DumpAsmRefs\bin\$(buildConfiguration)'
    Contents: |
      **\*.nupkg
      **\*.snupkg
      **\RELEASE_*
    TargetFolder: '$(Build.ArtifactStagingDirectory)\packages'

- task: VSTest@2
  displayName: 'Unit tests'
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    codeCoverageEnabled: true
    testSelector: testAssemblies
    testAssemblyVer2: |
      **\DumpAsmRefs.Tests.dll
      !**\obj\**

- task: SonarCloudAnalyze@1

- task: VSTest@2
  enabled: true
  displayName: 'End-to-end build tests'
  timeoutInMinutes: 5
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    testSelector: testAssemblies
    testAssemblyVer2: |
      **\DumpAsmRefs.MSBuild.Tests.dll
      !**\obj\**

- task: CopyFiles@2
  condition: failed()
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\tests\TestResults'
    Contents: |
      nuget.config
      **\*.binlog
    TargetFolder: '$(Build.ArtifactStagingDirectory)\e2eBinLogs'

- task: PublishPipelineArtifact@1
  condition: failed()
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)\e2eBinLogs'
    artifact: 'e2eBinLogs'
    publishLocation: 'pipeline'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)\binaries'
    artifact: 'binaries'
    publishLocation: 'pipeline'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)\packages'
    artifact: 'packages'
    publishLocation: 'pipeline'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'