# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net
name: 'CI build, test and end-to-end test'

trigger:
  - master
  - branch-*

pr:
  - master
  - branch-*

jobs:
  - job: buildAndUnitTest
    displayName: 'Build and unit test'
    pool:
      vmImage: 'windows-latest'

    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarCloud - Devtility'
        organization: 'devtility'
        scannerMode: 'MSBuild'
        projectKey: 'asmrefs-baseliner'
        projectName: 'AsmRefs Baseliner'
        projectVersion: '0.1'

    - task: VSBuild@1
      displayName: 'Build product and tests'
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: CopyFiles@2
      displayName: 'Copy E2E test binaries to staging directory "e2ebinaries"'
      enabled: true
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/tests/DumpAsmRefs.MSBuild.Tests/bin/$(buildConfiguration)/'
        Contents: |
          **/*
        TargetFolder: '$(Build.ArtifactStagingDirectory)/e2ebinaries'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish "E2E test binaries"'
      enabled: true
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/e2ebinaries'
        artifact: 'e2ebinaries'
        publishLocation: 'pipeline'

    - task: CopyFiles@2
      displayName: 'Copy binaries to staging directory "binaries"'
      enabled: false
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)\src\DumpAsmRefs\bin'
        Contents: |
          **\dump**
          **\Microsoft.Extensions**
        TargetFolder: '$(Build.ArtifactStagingDirectory)\binaries'

    - task: CopyFiles@2
      displayName: 'Copy release artefacts to staging directory "packages"'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)\src\DumpAsmRefs\bin\$(buildConfiguration)'
        Contents: |
          **\*.nupkg
          **\*.snupkg
          **\RELEASE_*
        TargetFolder: '$(Build.ArtifactStagingDirectory)\packages'

    - task: VSTest@2
      displayName: 'Unit tests'
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        codeCoverageEnabled: true
        testSelector: testAssemblies
        testAssemblyVer2: |
          **\DumpAsmRefs.Tests.dll
          !**\obj\**

    - task: SonarCloudAnalyze@1

    - task: PublishPipelineArtifact@1
      displayName: 'Publish "binaries"'
      enabled: false
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)\binaries'
        artifact: 'binaries'
        publishLocation: 'pipeline'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish "packages"'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)\packages'
        artifact: 'packages'
        publishLocation: 'pipeline'

    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'

    - task: VSTest@2
      enabled: false
      displayName: 'End-to-end build tests'
      timeoutInMinutes: 5
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        testSelector: testAssemblies
        testAssemblyVer2: |
          **\DumpAsmRefs.MSBuild.Tests.dll
          !**\obj\**

  - job: e2etests
    displayName: 'End to end tests'
    dependsOn: 'buildAndUnitTest'

    pool:
      vmImage: 'windows-latest'

    steps:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download test binaries'
      inputs:
        buildType: 'current'
        artifactName: 'e2ebinaries'
        targetPath: '$(Pipeline.Workspace)'
       
    - task: DotNetCoreCLI@2
      displayName: 'DotNet e2e tests - netcoreapp3.0'
      inputs:
        command: custom
        custom: vstest
        arguments: DumpAsmRefs.MSBuild.Tests.dll --Logger:trx
        workingDirectory: '$(Pipeline.Workspace)/e2ebinaries/netcoreapp3.0/'

    - task: DotNetCoreCLI@2
      displayName: 'DotNet e2e tests - net48 '
      inputs:
        command: custom
        custom: vstest
        arguments: DumpAsmRefs.MSBuild.Tests.dll  --Logger:trx
        workingDirectory: '$(Pipeline.Workspace)/e2ebinaries/net48/'

    - task: PublishTestResults@2
      displayName: 'Publish dotnet e2e test results'
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '**/*.trx'
        mergeTestResults: true
        testRunTitle: 'E2E tests'
        searchFolder: '$(Pipeline.Workspace)/e2ebinaries/'

    - task: CopyFiles@2
      displayName: '(on failure) Copy e2e test outputs to staging directory "e2eBinLogs"'
      condition: failed()
      inputs:
        SourceFolder: '$(Pipeline.Workspace)/e2ebinaries/'
        Contents: |
          **/nuget.config
          **/*.binlog
        TargetFolder: '$(Build.ArtifactStagingDirectory)/e2eBinLogs'

    - task: PublishPipelineArtifact@1
      displayName: '(on failure) Publish "e2eBinLogs"'
      condition: failed()
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)\e2eBinLogs'
        artifact: 'e2eBinLogs'
        publishLocation: 'pipeline'
