//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DumpAsmRefs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DumpAsmRefs.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report file does not exist.
        /// </summary>
        internal static string CompareTask_Error_ReportNotFound {
            get {
                return ResourceManager.GetString("CompareTask_Error_ReportNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring source assembly public key tokens: {0}.
        /// </summary>
        internal static string CompareTask_IgnoreSourcePublicKeyToken {
            get {
                return ResourceManager.GetString("CompareTask_IgnoreSourcePublicKeyToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplied VersionCompatibility is invalid: {0}. Allowed values: {1}.
        /// </summary>
        internal static string CompareTask_InvalidVersionCompat {
            get {
                return ResourceManager.GetString("CompareTask_InvalidVersionCompat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenced assemblies are different. Compare the baseline and current files to see the details.
        ///    Baseline: {0}
        ///    Current: {1}.
        /// </summary>
        internal static string CompareTask_ReferencesAreDifferent {
            get {
                return ResourceManager.GetString("CompareTask_ReferencesAreDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenced assemblies have not changed.
        ///    Baseline: {0}
        ///    Current: {1}.
        /// </summary>
        internal static string CompareTask_ReferencesAreSame {
            get {
                return ResourceManager.GetString("CompareTask_ReferencesAreSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly version compatibility level: {0}.
        /// </summary>
        internal static string CompareTask_VersionCompat {
            get {
                return ResourceManager.GetString("CompareTask_VersionCompat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} matches.
        /// </summary>
        internal static string Matching_MatchesFound {
            get {
                return ResourceManager.GetString("Matching_MatchesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching files.
        /// </summary>
        internal static string Matching_NoFiles {
            get {
                return ResourceManager.GetString("Matching_NoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches:.
        /// </summary>
        internal static string Matching_ResultListHeader {
            get {
                return ResourceManager.GetString("Matching_ResultListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string Matching_ResultListItem {
            get {
                return ResourceManager.GetString("Matching_ResultListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root directory for files matches: {0}.
        /// </summary>
        internal static string Matching_RootDirectory {
            get {
                return ResourceManager.GetString("Matching_RootDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output report file name.
        /// </summary>
        internal static string Parser_ArgDescription_File {
            get {
                return ResourceManager.GetString("Parser_ArgDescription_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root search directory.
        /// </summary>
        internal static string Parser_ArgDescription_Root {
            get {
                return ResourceManager.GetString("Parser_ArgDescription_Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging verbosity level.
        /// </summary>
        internal static string Parser_ArgDescription_Verbosity {
            get {
                return ResourceManager.GetString("Parser_ArgDescription_Verbosity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid verbosity option &quot;{0}&quot;.
        /// </summary>
        internal static string Parser_Error_InvalidVerbosity {
            get {
                return ResourceManager.GetString("Parser_Error_InvalidVerbosity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide at least one include pattern.
        /// </summary>
        internal static string Parser_IncludePatternRequired {
            get {
                return ResourceManager.GetString("Parser_IncludePatternRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string Program_Finished {
            get {
                return ResourceManager.GetString("Program_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report file written: {0}.
        /// </summary>
        internal static string Program_ReportFileWritten {
            get {
                return ResourceManager.GetString("Program_ReportFileWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ################################
        ///# Assembly references report
        ///# Report date/time: {0}
        ///################################
        ///#
        ///# Generated by Devtility CheckAsmRefs v{1}
        ///# For more information see https://github.com/devtility/asmref-baseliner/
        ///#
        ///#
        ///# Build failure instructions
        ///# --------------------------
        ///# If the build fails:
        ///# * Compare the new report against the baseline report to see what has changed
        ///#    (i.e. new references, versions changed, references removed)
        ///# * If the changes are not ok, f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Report_HeaderInstructions {
            get {
                return ResourceManager.GetString("Report_HeaderInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report file does not exist.
        /// </summary>
        internal static string ReportComparer_Error_ReportNotFound {
            get {
                return ResourceManager.GetString("ReportComparer_Error_ReportNotFound", resourceCulture);
            }
        }
    }
}
